package com.santhosh.hibernate;

// Generated May 17, 2012 6:00:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "hibernatetest")
public class Customer implements java.io.Serializable {

	private int id;

	public Customer() {
	}

	public Customer(int id) {
		this.id = id;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
