package com.santhosh.hibernate;

// Generated May 17, 2012 5:36:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private ProductId id;
	private Long price;
	private Set<ProductOrder> productOrders = new HashSet<ProductOrder>(0);

	public Product() {
	}

	public Product(ProductId id) {
		this.id = id;
	}

	public Product(ProductId id, Long price, Set<ProductOrder> productOrders) {
		this.id = id;
		this.price = price;
		this.productOrders = productOrders;
	}

	public ProductId getId() {
		return this.id;
	}

	public void setId(ProductId id) {
		this.id = id;
	}

	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	public Set<ProductOrder> getProductOrders() {
		return this.productOrders;
	}

	public void setProductOrders(Set<ProductOrder> productOrders) {
		this.productOrders = productOrders;
	}

}
