package com.santhosh.hibernate;

// Generated May 17, 2012 5:36:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProductId generated by hbm2java
 */
public class ProductId implements java.io.Serializable {

	private int category;
	private int id;

	public ProductId() {
	}

	public ProductId(int category, int id) {
		this.category = category;
		this.id = id;
	}

	public int getCategory() {
		return this.category;
	}

	public void setCategory(int category) {
		this.category = category;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductId))
			return false;
		ProductId castOther = (ProductId) other;

		return (this.getCategory() == castOther.getCategory())
				&& (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCategory();
		result = 37 * result + this.getId();
		return result;
	}

}
